### ISSUE TITLE
Enhancement Suggestion - Bugfix Options

### ISSUE THREAD

**Issue by Wobin** [Darktide-Mod-Framework/Darktide-Mod-Framework#14]
A suggestion, perhaps we could have a section in the mod options to include our individual mod options as a sub-item under "Bugfixes" or similar, so it doesn't necessarily clutter up the main mod options menu, especially if there are only the 'toggle on' or one or two other settings set.

**Comment by danreeves** [comment]
Braindump:

- VMF let you search the mod list and IIRC persisted the search between opening and closing the menu
- VMF allowed you to pin mods to the top of the mod options 
- I think VMF also persisted which mod was open and closed (vmf was more an accordion than the nested menu we have in dmf but I think the feature still applies)

So some enhancements I could see dmf having:
- allow searching the mod options list
- Allow reordering or pinning mods in the options list
- Maintain which mod you’ve got selected between closing and opening the menu for when you’re going back and forth tweaking something 
- Compress all the mods that only have an on/off toggle into a single page

**Comment by Wobin** [comment]
I apologise, I put this in the wrong repo! Could it be shifted to the DMF repo?

**Comment by danreeves** [comment]
Oh. hehe i didn't notice that. I'm not able to but @Aussiemon should be

**Comment by sclu1034** [comment]
I wouldn't make it a section specific to bug fixes (or any one category) only. And I'd draw the line at "has no options except for the toggle", otherwise that extra section would need to implement the entire set of customizable widgets again, and we would basically end up with two entire mod option views.

But I could see the view being reworked such that there is one fixed section where all mods are listed with their enable toggle, and extra sections for each mod are only added if they have extra options themselves (and maybe only if enabled).

**Comment by Aussiemon** [comment]
> I wouldn't make it a section specific to bug fixes (or any one category) only. And I'd draw the line at "has no options except for the toggle", otherwise that extra section would need to implement the entire set of customizable widgets again, and we would basically end up with two entire mod option views.
> 
> But I could see the view being reworked such that there is one fixed section where all mods are listed with their enable toggle, and extra sections for each mod are only added if they have extra options themselves (and maybe only if enabled).

I like this idea. I made untogglable mods appear in Mod Options so the user could have a clear picture of their mod load order ingame, but it'd be cleaner if this was moved to a single category with the toggles alongside.
