### ISSUE TITLE
Keybind issues

### ISSUE THREAD

**Issue by Aussiemon** [Darktide-Mod-Framework/Darktide-Mod-Framework#34]
Current behavior:

1. For all keybinds, check if their primary key is pressed
2. If true, check that all their enablers are pressed
3. If true, check that no additional modifier keys are pressed
4. If a keybind is held, wait for it to be released before checking additional keybinds

Flaws:

Can't hold a mod hotkey and use a different mod hotkey.
Supports limited subset of keys - no mouse buttons, no modifier keys as primary keybinds.

New behavior copies the vanilla keybind system with DMF's events and actions:

1. For all keybinds, check their evaluation function (main key + enablers + disablers)
2. If true and not already pressed, try to perform the keybind action
3. If successful, mark the keybind as pressed
4. If the evaluation function is false and the keybind is pressed, perform the release action and set unpressed

**Comment by Wobin** [comment]
Attempting to set a keybind that includes the DMF Options keybind fails. IE, setting a keybind to 'Ctrl-F4' does not register, as pressing the F4, sets it back to opening the options.

**Comment by Aussiemon** [comment]
> 

Addressed in https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/pull/33/commits/1755759432eb21228673c9c07a6806d6768d6605
