### ISSUE TITLE
mod:get_internal_data('options') doesn't exist but the documentation says it should

### ISSUE THREAD

**Issue by FatNutt** [Darktide-Mod-Framework/Darktide-Mod-Framework#43]
Issue: Base of the documentation [here](https://dmf-docs.darkti.de/#/mod-data), using dmf you should be able to get the mod data options defined in `modname_data.lua` using `mod:get_internal_data('options')` but it returns nil every time.

I would have expected it to be defined in [dmf_mod_manager.lua](https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/blob/master/dmf/scripts/mods/dmf/modules/dmf_mod_manager.lua) in `dmf.initialize_mod_data`

If this is intentional then I think the documentation should be updated to reflect it so that others aren't confused.

If this is **not** intentional, then I'd be happy to make a branch and get a PR going for this.

Looking forward to feedback.

**Comment by fracticality** [comment]
Looking back through VMF (of which DMF is a port), no such 'options' key appears to have ever existed.

I think it makes more sense to remove it from the documentation, which I've done.
