### ISSUE TITLE
command list gui

### ISSUE THREAD

**Issue by deluxghost** [Darktide-Mod-Framework/Darktide-Mod-Framework#8]
![image](https://user-images.githubusercontent.com/5835759/222533385-cef706bc-c4da-4cfb-a796-3e9f9fc99329.png)

1. the font is not locale specific one, so CJK characters cannot display properly

![image](https://user-images.githubusercontent.com/5835759/222533757-f6235d14-4fd4-4adb-a269-3810fa4df99e.png)

2. the text lines are bottom up

**Comment by Aussiemon** [comment]
I have a fix for 1: 
![image](https://user-images.githubusercontent.com/13663574/224590063-f4e27d43-f55a-4265-b18d-64225b09014c.png)

**Comment by Aussiemon** [comment]
and 2:
![image](https://user-images.githubusercontent.com/13663574/224592325-a2566329-2fc1-4c9a-9de7-ec3a378de6bf.png)

**Comment by Aussiemon** [comment]
Fixed in https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/commit/3182e06c252dd43a40b95867fdc425033d380466 and https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/commit/76e6d748b65e6ef8685e179769817af7a2f5476f

**Comment by deluxghost** [comment]
@Aussiemon Good fix! In addition, I think you could also change the layout slightly. See the bottom side (part of the text is out of bound) and the right side (`[...]` part is so close to the border)

**Comment by Aussiemon** [comment]
> @Aussiemon Good fix! In addition, I think you could also change the layout slightly. See the bottom side (part of the text is out of bound) and the right side (`[...]` part is so close to the border)

The former turned out to be a simple fix: https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/commit/293ca07904e1ea3ca81fb9a2069e7fc67caf77fa#diff-435815cb5833633f5dcc11ccea691a84df2cc5ff5378132604edac57582f77b0
